### ISSUE TITLE
[ ] doesn't work, only array()

### ISSUE THREAD

**Issue by qg0** [battye/php-array-parser#1]
Works ok: 
`$value = "array(0 => array('one' => 1, 'two' => 'two', 3 => [1]));";`

It doesn't work: 
`"[0 => array('one' => 1, 'two' => 'two', 3 => [1])];"`

Stack trace:
```
PHP Fatal error:  Uncaught battye\array_parser\exception\parser_exception: [php-array-parser] Unexpected token - expecting T_ARRAY in /vendor/battye/php-array-parser/src/tokens.php:115
Stack trace:
#0 /vendor/battye/php-array-parser/src/parser.php(232): battye\array_parser\tokens->force_match()
#1 /vendor/battye/php-array-parser/src/parser.php(43): battye\array_parser\parser->parse_array()
#2 /test_array.php(9): battye\array_parser\parser::parse_simple()
#3 {main}
thrown in /vendor/battye/php-array-parser/src/tokens.php on line 115
```

**Comment by battye** [comment]
Hi @qg0 - thanks a lot for discovering this bug! I have fixed it in the [newest release v1.0.9](https://github.com/battye/php-array-parser/releases/tag/v1.0.9) and I've added a new unit test at [testParseStringStartingWithShortSyntax()](https://github.com/battye/php-array-parser/blob/master/tests/ArrayParserTest.php#L54) to cover the exact scenario you described.

If you notice any other issues, please do let me know. This library is used quite extensively in the phpBB customisation database and translation validator so I like to cover as many different array formatting styles as possible that the public might use.

Regarding this bug, it seems like it only impacts the simple parsing because there was no [initial check](https://github.com/battye/php-array-parser/blob/9927b2985b7b45d1e4ff516650850e8c14fa9f69/src/parser.php#L43) to see if it was using the shorthand syntax to open the array. Out of interest I tried running this on the regex parsing and it seemed to handle it well, thankfully:

```php
$file = __DIR__ . '/files/test_x2.php'; // file contains: [0 => array('one' => 1, 'two' => 'two', 3 => [1])]
$regex = '/[^"]+/x';
$result = parser::parse_regex($regex, $file, 0);

$expected = [[0 => array('one' => 1, 'two' => 'two', 3 => [1])]];

var_dump($expected);
var_dump($result[0]);
```

Both returned:

```
array(1) {
  [0]=>
  array(1) {
    [0]=>
    array(3) {
      ["one"]=>
      int(1)
      ["two"]=>
      string(3) "two"
      [3]=>
      array(1) {
        [0]=>
        int(1)
      }
    }
  }
}
```
